### ISSUE TITLE
Add options to reset form to original state and to set current state as the "clean" state (Question how do you set form back to clean?)

### ISSUE THREAD

**Issue by lenamtl** [simontaite/jquery.dirty#1]
Let say the form data are sent and saved in DB.
How can I set the form back to clean without reloading the page?

Thanks

**Comment by simontaite** [comment]
Hi @lenamtl,

At the moment there's no way to do this but I can see the use for it.
How about something like `$("form").dirty("resetForm")`?

This would then set the form back to original state, whether it is empty or with data that was populated on page load or whenever `$("form").dirty()` was originally invoked

**Comment by lenamtl** [comment]
Hi,
where do you take **resetForm** function?

**Comment by simontaite** [comment]
At the moment there is no `resetForm` function, I'll have to add one in.

I would expect a `resetForm` function to set the form back to it's original state, so it would not keep the new values

If you want to keep the new values, setting them as the 'clean' state of the form, that will also require a new feature, a `setAsClean` function

How are you reloading the page after saving the data? Have you set the `preventLeaving` option to `true`?

**Comment by lenamtl** [comment]
Ok that make sense.

Yes I'm using preventLeaving option to true.

I have tried this with no luck I guess there is a syntax error or maybe this is just not possible to use it like this
`echo '<script type="text/javascript"> $("#edit").dirty({preventLeaving:false}); location.reload(true); </script>';`

**Comment by simontaite** [comment]
The `preventLeaving` option here is simply doing its job
If we try to navigate away from the page in any way other than by submitting the form (or otherwise triggering the `submit` event) then the message will pop up of the form is dirty

Seems to me that if you have saved the form through some other method then there should be a `setAsClean` function exposed for you to call after confirming that the save was successful.
This will then stop the flag from being tripped and the message won't be shown when you call `location.reload(true);`

That sound reasonable?

**Comment by lenamtl** [comment]
yes this is what I need

**Comment by simontaite** [comment]
Awesome
I'll include `resetForm` and `setAsClean` in the next release, will use this issue to track them

Thanks for the feedback

**Comment by lenamtl** [comment]
Ok thanks

by the way there is a setClean function 
I have tried something like this with no luck, I guess this is because it should call for each fields..
`echo '<script type="text/javascript"> $("#edit").dirty("setClean"); </script>';`

**Comment by simontaite** [comment]
`setClean` and `setDirty` are internal methods for setting the state of the form when it detects values have changed, they're not designed to be consumed directly

**Comment by simontaite** [comment]
Hi @lenamtl,

Just pushed v0.3.0, thsi contains `resetForm` and `setAsClean`as new public methods. Consumed in teh usual way
e.g.
`$("#edit").dirty("setAsClean")`

If you're happy with these changes can you close the issue please?

**Comment by lenamtl** [comment]
Thanks I will do a test and get back to you

**Comment by simontaite** [comment]
Nope, the options are case insensitive, the switch is performed on the options after it has been changed to lowercase

**Comment by simontaite** [comment]
No feedback that there are issues with either `resetForm` or `setAsClean`
Closing issue
