### ISSUE TITLE
Possible problem with setAsDirty

### ISSUE THREAD

**Issue by lenamtl** [simontaite/jquery.dirty#10]
Hi,

I'm setting the form as dirty on page load  `$("#add").dirty("setAsDirty");`
and if I quit the page it's not alerting and the button stay disable

How should I use it?

**Comment by simontaite** [comment]
Oops, this is related to #8, where the setting of isDirty/isClean wasn't triggering the appropriate events
Sorry for the inconvenience

This has been resolved in v0.7.1
https://www.npmjs.com/package/jquery.dirty/v/0.7.1
