### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by lenamtl** [simontaite/jquery.dirty#11]
Hi,

I'm using an hybrid version a mix of yours and the original dirrty script.

I'm using this datepicker https://github.com/uxsolutions/bootstrap-datepicker
If I enable the datepicker clear button `clearBtn: true,` 
this is not triggering a change when I clear the value and not enabling the save button

Any clue how I could handle this case?

**Comment by mkllnk** [comment]
I have a similar problem and I think that the `onClean` event doesn't fire because the clean state is not detected.

**Comment by simontaite** [comment]
Closed by #31
