### ISSUE TITLE
StopImmediatePropagation conflicts with other behaviors 

### ISSUE THREAD

**Issue by maxence51** [simontaite/jquery.dirty#22]
Hello,

I have an issue caused by the `stopImmediatePropagation` at the end of `checkValues`.

This prevent other subscribers to react to key press on form. In my example, jquery validation do not validate input field after key has been pressed.

**Comment by Niksac** [comment]
same here,
the change() event on my checkboxes does not work when using this plugin.

**Comment by simontaite** [comment]
Hi @maxence51, @Niksac 

Thank you for bringing this to my attention, apologies for the delay in addressing it
I've published v0.8.0 to npm, which addresses this issue
