### ISSUE TITLE
How to add detection to a tab?

### ISSUE THREAD

**Issue by lenamtl** [simontaite/jquery.dirty#3]
I'm having 2 differents forms on tabs (bootstrap tabs)
tab1 = form1
tab2 = form2

Let say a user made a change on tab1 form and click on a tab2, I want to detect this even as a quit before saving.

What will be the best way to do it?

**Comment by simontaite** [comment]
The form is still on the page at that point so if you want to perform any action based on changing the tab you'll have to attach to that event instead

You can attach to the bootstrap tab switch event as demonstrated here https://stackoverflow.com/a/26147163/2710589

**Comment by lenamtl** [comment]
ok thanks I will check that

**Comment by simontaite** [comment]
Closing due to lack of response

**Comment by lenamtl** [comment]
Hi,

I was very busy so here what I did as a quick solution

Each form have the dirty script and each tab have a form.
When form is dirty it add a color to corresponding tab when it is clean I remove that color.
So the user get alerted when he try to quit the page the regular way and the tab color indicate which form tab need to be saved. 

When I will have more time I will add a real tab detection.
