### ISSUE TITLE
Question how to handle Chained dropdown Ajax ?

### ISSUE THREAD

**Issue by lenamtl** [simontaite/jquery.dirty#5]
Hi, 
I'm using select2.js and Ajax for chained drop down 
Country, State, City

If the field are empty on page load then if I select items, then clear all 3 fields  I'm getting the form dirty...
This seems related to when the code call .empty();

I saw that you have a refreshEvents is this something that could use for this problem?

Thanks

**Comment by simontaite** [comment]
Hi,

This isn't  scenario I had previously considered, do you have a jsfiddle that can replicate the issue?

**Comment by lenamtl** [comment]
I figured out what the problem is
my code do this to clear the field when selecting a country $('#quote_city_id').empty();
so if I consol.log the value is not considered empty but NULL...
So the field was fisrt " " then NULL so the data changed = dirty...

To fixt this, after $('#quote_city_id').empty(); I prepend an empty value like this $('#quote_city_id').prepend("<option value='' selected='selected'>Select</option>"); 
so the value get back to empty instead of NULL so it's not considered as dirty ...
