### ISSUE TITLE
on change event of select box stopped working

### ISSUE THREAD

**Issue by Makrambg** [simontaite/jquery.dirty#6]
I have a form that contains a select box, after adding the dirty to the form, the events on the select box stopped working.

**Comment by lenamtl** [comment]
You probably have a JS error..
use Chrome right click and select Inspect
check the console to see if there is an error.
you can try to reproduce the problem and check the console sometimes the error only appear when we use the element.
If no error, are you using a specific plugin for the select?

**Comment by simontaite** [comment]
Is this still an issue?

**Comment by simontaite** [comment]
Closing due to lack of response

**Comment by lenamtl** [comment]
I Never reproduced
