### ISSUE TITLE
How to use it with upload file?

### ISSUE THREAD

**Issue by lenamtl** [simontaite/jquery.dirty#7]
Is jquery.dirty will work with input type file?

I'm using jquery.filer.js 
the `<input type="file" name="files[]">` 
once I have upload a file and remove the file it still getting  `data-is-dirrty="true"`

Here is a demo of jquery.filer as the project is no longer available on Github... https://www.tutorialspoint.com/jquery/src/filer/index.htm

Thanks

**Comment by simontaite** [comment]
Hi,

Support for input file types is now available in v0.7.0
https://www.npmjs.com/package/jquery.dirty/v/0.7.0

Thanks

**Comment by lenamtl** [comment]
Thanks I will try it
