### ISSUE TITLE
setAsClean does not trigger onClean

### ISSUE THREAD

**Issue by santiagodoldan** [simontaite/jquery.dirty#8]
I was wondering why setAsClean isn't triggering the onClean callback, if there is no reason, I'd like to create a PR and add it, just wanted to know before working on it.

*Same thing for resetForm

**Comment by simontaite** [comment]
No reason, complete oversight on my part
A PR would be more than welcome

**Comment by simontaite** [comment]
This has been resolved in v0.7.1
