### ISSUE TITLE
Is there any setAsDirty

### ISSUE THREAD

**Issue by lenamtl** [simontaite/jquery.dirty#9]
Hi,

I have a case that a form is pre-filled with some data, so I need to set the form to **dirty** on page load.

Do I need to create a setAsDirty or is there a way to call an existing function to do it setDirty?

Any help or guidance is welcome 
Thanks

**Comment by simontaite** [comment]
Hi,

setAsDirty is now available in v0.7.0
https://www.npmjs.com/package/jquery.dirty/v/0.7.0

Thanks

**Comment by lenamtl** [comment]
Thanks a lot
